version: '3.8'
name: ht6-server
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_PLUGINS: 'dump-zip dump-json'
      ADMINER_DESIGN: flat
    ports:
      - 8080:8080
  smtp:
    image: jcalonso/mailhog
    restart: always
    ports:
      - 8025:8025
      - ${SMTP_PORT}:1025
  keycloaker:
    image: quay.io/keycloak/keycloak
    command: ['start-dev', '--import-realm']
    restart: always
    ports:
      - 8050:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - db
